import { DocumentTemplate } from '../types/template';

export const PLAN_TEMPLATE: DocumentTemplate = {
  id: 'plan-v1',
  documentType: 'PLAN',
  version: '1.0',
  customSectionsAllowed: false,
  frontmatterDefaults: {
    status: 'draft',
    version: '1.0',
    depth: 2,
    sibling_index: 0,
    sibling_count: 1,
    execution_mode: 'sequential',
    priority: 'normal',
    traces_from: [],
    traces_to: [],
    depends_on: [],
    dependency_type: [],
  },
  sections: [
    {
      id: 'objective',
      heading: 'Objective',
      level: 2,
      required: true,
      description: 'Clear statement of what this plan aims to achieve and its success criteria',
      minWordCount: 80,
      subsections: [],
      rubricCategoryId: 'completeness',
    },
    {
      id: 'scope',
      heading: 'Scope',
      level: 2,
      required: true,
      description: 'Boundaries of this plan: what is included, what is excluded, and why',
      minWordCount: 80,
      subsections: [],
      rubricCategoryId: 'completeness',
    },
    {
      id: 'tasks',
      heading: 'Tasks',
      level: 2,
      required: true,
      description: 'Ordered list of implementation tasks with descriptions, effort estimates, and assignees',
      minWordCount: 200,
      subsections: [],
      rubricCategoryId: 'task_granularity',
    },
    {
      id: 'dependencies',
      heading: 'Dependencies',
      level: 2,
      required: true,
      description: 'Task dependencies, blocking relationships, and execution ordering constraints',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'dependency_accuracy',
    },
    {
      id: 'testing-strategy',
      heading: 'Testing Strategy',
      level: 2,
      required: true,
      description: 'How the work in this plan will be tested, including integration and acceptance tests',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'acceptance_criteria',
    },
    {
      id: 'risks',
      heading: 'Risks',
      level: 2,
      required: true,
      description: 'Identified risks, their likelihood and impact, and mitigation strategies',
      minWordCount: 80,
      subsections: [],
      rubricCategoryId: 'risk_identification',
    },
    {
      id: 'definition-of-done',
      heading: 'Definition of Done',
      level: 2,
      required: true,
      description: 'Explicit criteria that must be met for this plan to be considered complete',
      minWordCount: 60,
      subsections: [],
      rubricCategoryId: 'acceptance_criteria',
    },
  ],
};
