/**
 * PRD template for observation-to-PRD promotion (SPEC-007-4-3, Task 7).
 *
 * Matches the template from TDD section 3.12.2.
 * Generates a pipeline-compatible PRD with YAML frontmatter fields:
 *   title, version, date, author, status, source, observation_id, severity, service.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Structured data extracted from an observation report's frontmatter
 * and body, used to populate the PRD template.
 */
export interface ObservationData {
  /** Observation ID (e.g., "OBS-20260408-143022-a7f3") */
  id: string;
  /** Service name */
  service: string;
  /** Repository name */
  repo: string;
  /** Severity level (e.g., "P1", "P2") */
  severity: string;
  /** Confidence score (0-1) */
  confidence: number;
  /** Fingerprint hash */
  fingerprint: string;
  /** Evidence text extracted from the observation body */
  evidence: string;
  /** Target metric name (e.g., "error_rate", "latency_p99_ms") */
  targetMetric: string;
  /** Current (broken) metric value */
  currentValue: string;
  /** Baseline (expected) metric value */
  baselineValue: string;
}

/**
 * Content generated by the LLM for PRD sections.
 */
export interface LlmPrdContent {
  /** Concise fix title (e.g., "Fix Connection Pool Exhaustion in Orders DB") */
  title: string;
  /** 2-3 sentences describing the problem with quantitative metrics */
  problemStatement: string;
  /** What the fix should address, based on the recommended action */
  scope: string;
}

// ---------------------------------------------------------------------------
// Template constants
// ---------------------------------------------------------------------------

export const PRD_AUTHOR = 'Production Intelligence Loop';
export const PRD_STATUS = 'Draft';
export const PRD_SOURCE = 'production-intelligence';
export const PRD_VERSION = '1.0';

// ---------------------------------------------------------------------------
// PRD generation prompt
// ---------------------------------------------------------------------------

export const PRD_GENERATION_PROMPT = `
You are generating a Product Requirements Document for a production fix.

## Observation Report
{observation_report_full_text}

## Service Configuration
- Service: {service}
- Repo: {repo}
- Criticality: {criticality}

## Previous Observations (same service, last 30 days)
{previous_observations_summary}

## Instructions
Generate the following sections:
1. **title**: A concise fix title (e.g., "Fix Connection Pool Exhaustion in Orders DB")
2. **problemStatement**: 2-3 sentences describing the problem with quantitative metrics
3. **scope**: What the fix should address, based on the recommended action

Respond in this exact JSON format:
{
  "title": "...",
  "problemStatement": "...",
  "scope": "..."
}
`;

// ---------------------------------------------------------------------------
// Frontmatter serializer
// ---------------------------------------------------------------------------

/**
 * Serializes a flat key-value record into YAML frontmatter block.
 * Uses a simple serializer that handles the types we produce
 * (strings, numbers, booleans, null).
 */
export function serializePrdFrontmatter(
  fields: Record<string, string | number | boolean | null>,
): string {
  const lines: string[] = ['---'];

  for (const [key, value] of Object.entries(fields)) {
    if (value === undefined) continue;
    lines.push(`${key}: ${serializeValue(value)}`);
  }

  lines.push('---');
  return lines.join('\n') + '\n';
}

function serializeValue(value: string | number | boolean | null): string {
  if (value === null) return 'null';
  if (typeof value === 'boolean') return String(value);
  if (typeof value === 'number') return String(value);
  if (typeof value === 'string') {
    // Quote strings that contain special YAML characters
    if (
      value.includes(':') ||
      value.includes('#') ||
      value.includes('[') ||
      value.includes(']') ||
      value.includes(',') ||
      value.includes('"') ||
      value.includes("'") ||
      value === 'true' ||
      value === 'false' ||
      value === 'null' ||
      value === '~' ||
      value === '' ||
      /^-?\d+(\.\d+)?$/.test(value)
    ) {
      return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
    }
    return value;
  }
  return String(value);
}

// ---------------------------------------------------------------------------
// Template builder
// ---------------------------------------------------------------------------

/**
 * Builds the complete PRD Markdown content from observation data and
 * LLM-generated content.
 *
 * The output is compatible with the existing autonomous development
 * pipeline format (TDD-001). Frontmatter includes:
 *   title, version, date, author, status, source, observation_id, severity, service.
 *
 * Body includes:
 *   - Problem Statement with quantitative metrics
 *   - Evidence copied from observation
 *   - Constraints referencing the observation
 *   - Success Criteria table
 *   - Scope
 *
 * @param prdId     The generated PRD ID (e.g., "PRD-OBS-20260408-143022-a7f3")
 * @param observation Structured observation data
 * @param llmContent  LLM-generated PRD sections
 * @returns Complete Markdown string with frontmatter
 */
export function buildPrdContent(
  prdId: string,
  observation: ObservationData,
  llmContent: LlmPrdContent,
): string {
  const frontmatterFields: Record<string, string | number | boolean | null> = {
    title: `Fix: ${llmContent.title}`,
    version: PRD_VERSION,
    date: new Date().toISOString().split('T')[0],
    author: PRD_AUTHOR,
    status: PRD_STATUS,
    source: PRD_SOURCE,
    observation_id: observation.id,
    severity: observation.severity,
    service: observation.service,
  };

  const frontmatter = serializePrdFrontmatter(frontmatterFields);

  const body = `
# ${llmContent.title}

## Problem Statement

${llmContent.problemStatement}

## Evidence

${observation.evidence}

## Constraints

- Fix must address the root cause identified in observation ${observation.id}
- Target metric: ${observation.targetMetric} must improve by at least 10% post-deployment
- Service: ${observation.service}, Repo: ${observation.repo}

## Success Criteria

| Metric | Current (broken) | Target (fixed) | Measurement |
|--------|-----------------|----------------|-------------|
| ${observation.targetMetric} | ${observation.currentValue} | ${observation.baselineValue} | Prometheus query post-deploy |

## Scope

${llmContent.scope}
`;

  return frontmatter + body;
}

// ---------------------------------------------------------------------------
// Prompt builder
// ---------------------------------------------------------------------------

/**
 * Builds the LLM prompt for PRD generation by interpolating observation
 * data into the prompt template.
 *
 * @param observationFullText The full observation report markdown
 * @param service             Service name
 * @param repo                Repository name
 * @param severity            Severity/criticality level
 * @param previousSummary     Summary of previous observations (may be empty)
 * @returns Interpolated prompt string
 */
export function buildPrdPrompt(
  observationFullText: string,
  service: string,
  repo: string,
  severity: string,
  previousSummary: string,
): string {
  return PRD_GENERATION_PROMPT
    .replace('{observation_report_full_text}', observationFullText)
    .replace('{service}', service)
    .replace('{repo}', repo)
    .replace('{criticality}', severity)
    .replace('{previous_observations_summary}', previousSummary || 'None');
}
