#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# mock-claude.sh - Mock Claude CLI for smoke E2E testing
#
# Parses the real claude CLI flags and writes appropriate artifacts based on
# the --agent parameter. Designed to replace 'claude' on PATH during testing
# to avoid real Anthropic API spend.
#
# The smoke test copies this to <tmpdir>/bin/claude and puts that on PATH.
#
# Environment:
#   SMOKE_MOCK_FAIL=1    Exit 1 without writing phase-result (for negative tests)
#   SMOKE_MOCK_LOG       Log file for debug (defaults to /dev/null)
###############################################################################

# Parse arguments to extract key info
AGENT=""
REQ_DIR=""
PROJECT=""
PHASE_BUDGET=""
PROMPT=""

# Log invocation for debugging
echo "mock-claude invoked: $*" >> "${SMOKE_MOCK_LOG:-/dev/null}"
echo "mock-claude started - PID: $$" >> "${SMOKE_MOCK_LOG:-/dev/null}"

# Honor SMOKE_MOCK_FAIL before anything else (for negative testing)
if [[ "${SMOKE_MOCK_FAIL:-0}" == "1" ]]; then
    echo "mock-claude: SMOKE_MOCK_FAIL=1, failing" >> "${SMOKE_MOCK_LOG:-/dev/null}"
    exit 1
fi

# Handle --version flag (common check)
if [[ "$1" == "--version" ]]; then
    echo "claude-mock 2.1.139 (for smoke testing)"
    exit 0
fi

# Parse arguments to extract --agent, --add-dir values, and prompt
while [[ $# -gt 0 ]]; do
    case "$1" in
        --agent)
            AGENT="$2"
            shift 2
            ;;
        --add-dir)
            # First --add-dir is req_dir, second is project
            if [[ -z "$REQ_DIR" ]]; then
                REQ_DIR="$2"
            else
                PROJECT="$2"
            fi
            shift 2
            ;;
        --max-budget-usd)
            PHASE_BUDGET="$2"
            shift 2
            ;;
        --print|--output-format|--permission-mode)
            shift 2
            ;;
        -*)
            # Skip unknown flags (may have values)
            if [[ $# -gt 1 && "$2" != -* ]]; then
                shift 2
            else
                shift 1
            fi
            ;;
        *)
            # This should be the prompt (last positional arg)
            PROMPT="$1"
            shift 1
            ;;
    esac
done


echo "mock-claude parsed - agent: $AGENT, req_dir: $REQ_DIR, project: $PROJECT" >> "${SMOKE_MOCK_LOG:-/dev/null}"

# Derive phase from agent name or req_dir state.json
CURRENT_PHASE=""
if [[ -n "$REQ_DIR" && -f "$REQ_DIR/state.json" ]]; then
    CURRENT_PHASE=$(jq -r '.current_phase // "unknown"' "$REQ_DIR/state.json" 2>/dev/null || echo "unknown")
fi

echo "mock-claude detected phase: $CURRENT_PHASE" >> "${SMOKE_MOCK_LOG:-/dev/null}"

# Handle prd-author specially - write actual PRD artifact
if [[ "$AGENT" == "prd-author" ]]; then
    # Write PRD artifact
    mkdir -p "$PROJECT/docs/prd"
    cat > "$PROJECT/docs/prd/smoke-feature.md" <<'EOF'
# Smoke Feature

## Overview
This is a minimal PRD generated by the mock claude for smoke testing.

## Requirements
- Add hello-world functionality
- Verify E2E pipeline works

## Success Criteria
- Smoke test passes
- Artifact is created
EOF

    # Write phase-result-prd.json
    cat > "$REQ_DIR/phase-result-prd.json" <<'EOF'
{
  "status": "pass",
  "artifacts": [
    {
      "kind": "file",
      "path": "docs/prd/smoke-feature.md"
    }
  ],
  "feedback": "",
  "cost_usd": 0.01,
  "turns_used": 3,
  "completed_at": "2026-05-12T00:00:00Z"
}
EOF

else
    # For other agents, write a generic pass result
    RESULT_FILE="$REQ_DIR/phase-result-${CURRENT_PHASE}.json"
    cat > "$RESULT_FILE" <<EOF
{
  "status": "pass",
  "artifacts": [],
  "feedback": "",
  "cost_usd": 0.01,
  "turns_used": 2,
  "completed_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF
fi

# Output cost information that spawn-session.sh expects
jq -n '{
    "total_cost_usd": 0.01,
    "result": "success",
    "turns_used": 3,
    "reason": "completed"
}'

exit 0