import { QualityRubric } from '../pipeline/types/quality-rubric';
import { AggregationResult, ReviewOutput, Finding } from './score-aggregator';
import { getSectionsForCategory } from './section-mappings';
import { DocumentType } from '../pipeline/types/document-type';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface FloorViolation {
  category_id: string;
  reviewer_id: string;
  score: number;
  min_threshold: number;
}

export interface ApprovalDecision {
  outcome: 'approved' | 'changes_requested' | 'rejected';
  reasons: string[];
  auto_generated_findings: Finding[];
  threshold_met: boolean;
  has_critical_blocking: boolean;
  has_critical_reject: boolean;
  floor_violations: FloorViolation[];
}

// ---------------------------------------------------------------------------
// ApprovalEvaluator
// ---------------------------------------------------------------------------

export class ApprovalEvaluator {
  /**
   * Evaluates whether a document passes the review gate.
   *
   * Three-part approval check (TDD section 3.4.2):
   * 1. Aggregate score >= approval threshold
   * 2. No critical findings (reject = immediate reject, blocking = changes_requested)
   * 3. Per-category floor check (auto-generates major findings for violations)
   *
   * Decision flow:
   * - critical:reject => "rejected"
   * - NaN/Infinity aggregate => "changes_requested"
   * - All three pass => "approved"
   * - iteration_count >= max_iterations => "rejected"
   * - Otherwise => "changes_requested"
   */
  evaluate(
    aggregationResult: AggregationResult,
    reviewerOutputs: ReviewOutput[],
    rubric: QualityRubric,
    iterationCount: number,
    maxIterations: number
  ): ApprovalDecision {
    const reasons: string[] = [];
    const autoGeneratedFindings: Finding[] = [];

    // --- Part 2 (checked first per decision flow): Critical finding check ---
    const hasCriticalReject = this.hasCriticalRejectFinding(reviewerOutputs);
    const hasCriticalBlocking = this.hasCriticalBlockingFinding(reviewerOutputs);

    if (hasCriticalReject) {
      reasons.push('Critical finding with reject sub-classification found.');
      return {
        outcome: 'rejected',
        reasons,
        auto_generated_findings: [],
        threshold_met: aggregationResult.aggregate_score >= (rubric as RubricWithThreshold).approval_threshold,
        has_critical_blocking: hasCriticalBlocking,
        has_critical_reject: true,
        floor_violations: [],
      };
    }

    // --- NaN / Infinity check ---
    const aggregate = aggregationResult.aggregate_score;
    const threshold = (rubric as RubricWithThreshold).approval_threshold ?? 85;

    if (!Number.isFinite(aggregate)) {
      console.error(
        'ApprovalEvaluator: Aggregate score is NaN or Infinity.',
        JSON.stringify({
          aggregate,
          per_reviewer_scores: aggregationResult.per_reviewer_scores,
        })
      );
      reasons.push(`Aggregate score is not a finite number (${aggregate}).`);
      return {
        outcome: 'changes_requested',
        reasons,
        auto_generated_findings: [],
        threshold_met: false,
        has_critical_blocking: hasCriticalBlocking,
        has_critical_reject: false,
        floor_violations: [],
      };
    }

    // --- Part 1: Aggregate score check ---
    const thresholdMet = aggregate >= threshold;
    if (!thresholdMet) {
      reasons.push(
        `Aggregate score ${aggregate} is below the approval threshold of ${threshold}.`
      );
    }

    // --- Critical blocking (already computed) ---
    if (hasCriticalBlocking) {
      reasons.push('Critical finding with blocking sub-classification found.');
    }

    // --- Part 3: Per-category floor check ---
    const floorViolations = this.checkFloorViolations(
      reviewerOutputs,
      rubric
    );

    for (const violation of floorViolations) {
      const category = rubric.categories.find((c) => c.id === violation.category_id);
      const categoryName = category?.name ?? violation.category_id;

      // Derive section_id from section mappings for this category
      let sectionId = '';
      try {
        const documentType = rubric.documentType as DocumentType;
        const sections = getSectionsForCategory(documentType, violation.category_id);
        sectionId = sections.length > 0 ? sections[0] : '';
      } catch {
        sectionId = '';
      }

      const finding: Finding = {
        severity: 'major',
        section_id: sectionId,
        category_id: violation.category_id,
        description: `Category '${categoryName}' scored ${violation.score} by reviewer ${violation.reviewer_id}, below the minimum threshold of ${violation.min_threshold}.`,
        evidence: `Reviewer ${violation.reviewer_id} scored ${violation.score}/${violation.min_threshold}`,
        suggested_resolution: `Improve the quality of content in the '${categoryName}' area to meet the minimum standard of ${violation.min_threshold}/100.`,
      };

      autoGeneratedFindings.push(finding);
    }

    if (floorViolations.length > 0) {
      reasons.push(
        `${floorViolations.length} per-category floor violation(s) detected.`
      );
    }

    // --- Decision flow ---
    const allPass = thresholdMet && !hasCriticalBlocking && floorViolations.length === 0;

    if (allPass) {
      return {
        outcome: 'approved',
        reasons: [],
        auto_generated_findings: autoGeneratedFindings,
        threshold_met: true,
        has_critical_blocking: false,
        has_critical_reject: false,
        floor_violations: floorViolations,
      };
    }

    if (iterationCount >= maxIterations) {
      reasons.push(
        `Iteration count ${iterationCount} has reached or exceeded max iterations ${maxIterations}.`
      );
      return {
        outcome: 'rejected',
        reasons,
        auto_generated_findings: autoGeneratedFindings,
        threshold_met: thresholdMet,
        has_critical_blocking: hasCriticalBlocking,
        has_critical_reject: false,
        floor_violations: floorViolations,
      };
    }

    return {
      outcome: 'changes_requested',
      reasons,
      auto_generated_findings: autoGeneratedFindings,
      threshold_met: thresholdMet,
      has_critical_blocking: hasCriticalBlocking,
      has_critical_reject: false,
      floor_violations: floorViolations,
    };
  }

  /**
   * Checks if any reviewer has a finding with critical_sub === 'reject'.
   */
  private hasCriticalRejectFinding(reviewerOutputs: ReviewOutput[]): boolean {
    for (const output of reviewerOutputs) {
      for (const finding of output.findings) {
        if (finding.severity === 'critical' && finding.critical_sub === 'reject') {
          return true;
        }
      }
    }
    return false;
  }

  /**
   * Checks if any reviewer has a finding with critical_sub === 'blocking'.
   */
  private hasCriticalBlockingFinding(reviewerOutputs: ReviewOutput[]): boolean {
    for (const output of reviewerOutputs) {
      for (const finding of output.findings) {
        if (finding.severity === 'critical' && finding.critical_sub === 'blocking') {
          return true;
        }
      }
    }
    return false;
  }

  /**
   * Checks each reviewer's per-category scores against the category's minimumScore.
   * Returns all violations.
   */
  private checkFloorViolations(
    reviewerOutputs: ReviewOutput[],
    rubric: QualityRubric
  ): FloorViolation[] {
    const violations: FloorViolation[] = [];

    for (const category of rubric.categories) {
      const minThreshold = category.minimumScore;
      if (minThreshold === undefined || minThreshold === null) {
        continue;
      }

      for (const output of reviewerOutputs) {
        const catScore = output.category_scores.find(
          (cs) => cs.category_id === category.id
        );
        if (!catScore) {
          continue;
        }

        // Use the raw score (not resolved) for floor check -- the score field
        // represents the reviewer's assessment for this category
        const score = catScore.score;
        if (score < minThreshold) {
          violations.push({
            category_id: category.id,
            reviewer_id: output.reviewer_id,
            score,
            min_threshold: minThreshold,
          });
        }
      }
    }

    return violations;
  }
}

/**
 * Extended rubric type that includes the approval threshold.
 * The base QualityRubric does not include approval_threshold;
 * it comes from the review gate config. This interface allows
 * the evaluator to read it from the rubric object when provided.
 */
interface RubricWithThreshold extends QualityRubric {
  approval_threshold?: number;
}
