import { DocumentTemplate } from '../types/template';

export const CODE_TEMPLATE: DocumentTemplate = {
  id: 'code-v1',
  documentType: 'CODE',
  version: '1.0',
  customSectionsAllowed: true,
  frontmatterDefaults: {
    status: 'draft',
    version: '1.0',
    depth: 4,
    sibling_index: 0,
    sibling_count: 1,
    execution_mode: 'sequential',
    priority: 'normal',
    traces_from: [],
    traces_to: [],
    depends_on: [],
    dependency_type: [],
  },
  sections: [
    {
      id: 'overview',
      heading: 'Overview',
      level: 2,
      required: true,
      description: 'Summary of the code artifact, its purpose, and how it relates to the parent spec',
      minWordCount: 50,
      subsections: [],
      rubricCategoryId: 'completeness',
    },
    {
      id: 'implementation',
      heading: 'Implementation',
      level: 2,
      required: true,
      description: 'Source code with inline comments, organized by file and module',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'correctness',
    },
    {
      id: 'tests',
      heading: 'Tests',
      level: 2,
      required: true,
      description: 'Test code covering unit tests, edge cases, and integration tests',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'test_coverage',
    },
    {
      id: 'documentation',
      heading: 'Documentation',
      level: 2,
      required: true,
      description: 'API documentation, usage examples, and configuration notes',
      minWordCount: 50,
      subsections: [],
      rubricCategoryId: 'documentation',
    },
    {
      id: 'changelog',
      heading: 'Changelog',
      level: 2,
      required: true,
      description: 'Version history with changes made, referencing spec traceability',
      minWordCount: 30,
      subsections: [],
      rubricCategoryId: 'spec_conformance',
    },
  ],
};
