import { DocumentTemplate } from '../types/template';

export const PRD_TEMPLATE: DocumentTemplate = {
  id: 'prd-v1',
  documentType: 'PRD',
  version: '1.0',
  customSectionsAllowed: false,
  frontmatterDefaults: {
    status: 'draft',
    version: '1.0',
    depth: 0,
    sibling_index: 0,
    sibling_count: 1,
    execution_mode: 'sequential',
    priority: 'normal',
    traces_from: [],
    traces_to: [],
    depends_on: [],
    dependency_type: [],
  },
  sections: [
    {
      id: 'executive-summary',
      heading: 'Executive Summary',
      level: 2,
      required: true,
      description: 'High-level overview of the product direction',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'completeness',
    },
    {
      id: 'problem-statement',
      heading: 'Problem Statement',
      level: 2,
      required: true,
      description: 'The problem being solved and why it matters',
      minWordCount: 150,
      subsections: [],
      rubricCategoryId: 'user_value',
    },
    {
      id: 'goals-and-objectives',
      heading: 'Goals and Objectives',
      level: 2,
      required: true,
      description: 'Measurable goals and success criteria',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'scope_definition',
    },
    {
      id: 'user-stories',
      heading: 'User Stories',
      level: 2,
      required: true,
      description: 'Key user stories in standard format',
      minWordCount: 200,
      subsections: [],
      rubricCategoryId: 'user_value',
    },
    {
      id: 'functional-requirements',
      heading: 'Functional Requirements',
      level: 2,
      required: true,
      description: 'Detailed functional requirements',
      minWordCount: 300,
      subsections: [],
      rubricCategoryId: 'completeness',
    },
    {
      id: 'non-functional-requirements',
      heading: 'Non-Functional Requirements',
      level: 2,
      required: true,
      description: 'Performance, security, scalability requirements',
      minWordCount: 150,
      subsections: [],
      rubricCategoryId: 'feasibility',
    },
    {
      id: 'scope-and-constraints',
      heading: 'Scope and Constraints',
      level: 2,
      required: true,
      description: 'What is in/out of scope; known constraints',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'scope_definition',
    },
    {
      id: 'acceptance-criteria',
      heading: 'Acceptance Criteria',
      level: 2,
      required: true,
      description: 'Criteria for considering the PRD satisfied',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'acceptance_criteria',
    },
    {
      id: 'risks-and-mitigations',
      heading: 'Risks and Mitigations',
      level: 2,
      required: true,
      description: 'Identified risks and mitigation strategies',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'risk_assessment',
    },
  ],
};
