import { DocumentTemplate } from '../types/template';

export const SPEC_TEMPLATE: DocumentTemplate = {
  id: 'spec-v1',
  documentType: 'SPEC',
  version: '1.0',
  customSectionsAllowed: false,
  frontmatterDefaults: {
    status: 'draft',
    version: '1.0',
    depth: 3,
    sibling_index: 0,
    sibling_count: 1,
    execution_mode: 'sequential',
    priority: 'normal',
    traces_from: [],
    traces_to: [],
    depends_on: [],
    dependency_type: [],
  },
  sections: [
    {
      id: 'description',
      heading: 'Description',
      level: 2,
      required: true,
      description: 'Detailed description of what this specification covers and its relationship to the parent plan task',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'completeness',
    },
    {
      id: 'files-to-create-modify',
      heading: 'Files to Create/Modify',
      level: 2,
      required: true,
      description: 'Table of files that will be created or modified, with action type (create/modify) and purpose',
      minWordCount: 50,
      subsections: [],
      rubricCategoryId: 'precision',
    },
    {
      id: 'implementation-details',
      heading: 'Implementation Details',
      level: 2,
      required: true,
      description: 'Step-by-step implementation instructions with code signatures, algorithms, and data flow',
      minWordCount: 300,
      subsections: [],
      rubricCategoryId: 'precision',
    },
    {
      id: 'acceptance-criteria',
      heading: 'Acceptance Criteria',
      level: 2,
      required: true,
      description: 'Verifiable criteria that must be met for this spec to be considered implemented',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'testability',
    },
    {
      id: 'test-cases',
      heading: 'Test Cases',
      level: 2,
      required: true,
      description: 'Unit tests, integration tests, and edge cases that validate the implementation',
      minWordCount: 150,
      subsections: [],
      rubricCategoryId: 'testability',
    },
    {
      id: 'notes',
      heading: 'Notes',
      level: 2,
      required: false,
      description: 'Additional context, trade-off decisions, or implementation considerations',
      minWordCount: 0,
      subsections: [],
      rubricCategoryId: null,
    },
  ],
};
