import { DocumentTemplate } from '../types/template';

export const TDD_TEMPLATE: DocumentTemplate = {
  id: 'tdd-v1',
  documentType: 'TDD',
  version: '1.0',
  customSectionsAllowed: false,
  frontmatterDefaults: {
    status: 'draft',
    version: '1.0',
    depth: 1,
    sibling_index: 0,
    sibling_count: 1,
    execution_mode: 'sequential',
    priority: 'normal',
    traces_from: [],
    traces_to: [],
    depends_on: [],
    dependency_type: [],
  },
  sections: [
    {
      id: 'overview',
      heading: 'Overview',
      level: 2,
      required: true,
      description: 'High-level technical overview and architectural context for this design',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'completeness',
    },
    {
      id: 'architecture',
      heading: 'Architecture',
      level: 2,
      required: true,
      description: 'System architecture, component relationships, and design patterns used',
      minWordCount: 200,
      subsections: [],
      rubricCategoryId: 'architecture_quality',
    },
    {
      id: 'data-models',
      heading: 'Data Models',
      level: 2,
      required: true,
      description: 'Data structures, schemas, entity relationships, and storage decisions',
      minWordCount: 150,
      subsections: [],
      rubricCategoryId: 'technical_accuracy',
    },
    {
      id: 'api-design',
      heading: 'API Design',
      level: 2,
      required: true,
      description: 'Interface contracts, endpoint definitions, request/response formats',
      minWordCount: 200,
      subsections: [],
      rubricCategoryId: 'api_design',
    },
    {
      id: 'error-handling',
      heading: 'Error Handling',
      level: 2,
      required: true,
      description: 'Error taxonomy, recovery strategies, and failure mode analysis',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'error_handling',
    },
    {
      id: 'security',
      heading: 'Security',
      level: 2,
      required: true,
      description: 'Authentication, authorization, data protection, and threat mitigations',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'security_considerations',
    },
    {
      id: 'testing-strategy',
      heading: 'Testing Strategy',
      level: 2,
      required: true,
      description: 'Test levels, coverage targets, test data strategy, and testing tools',
      minWordCount: 150,
      subsections: [],
      rubricCategoryId: 'testing_strategy',
    },
    {
      id: 'deployment',
      heading: 'Deployment',
      level: 2,
      required: true,
      description: 'Deployment strategy, environment configuration, and rollback procedures',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'completeness',
    },
    {
      id: 'performance',
      heading: 'Performance',
      level: 2,
      required: true,
      description: 'Performance requirements, benchmarks, optimization strategies, and SLAs',
      minWordCount: 100,
      subsections: [],
      rubricCategoryId: 'technical_accuracy',
    },
    {
      id: 'monitoring',
      heading: 'Monitoring',
      level: 2,
      required: true,
      description: 'Observability strategy, metrics, alerting, and dashboards',
      minWordCount: 80,
      subsections: [],
      rubricCategoryId: 'completeness',
    },
    {
      id: 'dependencies',
      heading: 'Dependencies',
      level: 2,
      required: true,
      description: 'External dependencies, third-party services, and version constraints',
      minWordCount: 80,
      subsections: [],
      rubricCategoryId: 'architecture_quality',
    },
    {
      id: 'migration',
      heading: 'Migration',
      level: 2,
      required: true,
      description: 'Data migration plan, backward compatibility, and rollback strategy',
      minWordCount: 80,
      subsections: [],
      rubricCategoryId: 'technical_accuracy',
    },
    {
      id: 'appendices',
      heading: 'Appendices',
      level: 2,
      required: false,
      description: 'Supporting diagrams, reference materials, and supplementary information',
      minWordCount: 0,
      subsections: [],
      rubricCategoryId: null,
    },
  ],
};
