/**
 * Observation report generator (SPEC-007-4-1, Task 1).
 *
 * Transforms candidate observations from the analytics engine into
 * YAML-frontmatter + Markdown files matching the full report format
 * from TDD section 3.9.2.
 *
 * The generated report includes:
 *   - YAML frontmatter with all schema fields (TDD section 4.1)
 *   - Markdown body: summary, severity rationale, evidence, root cause
 *     hypothesis with disclaimer, recommended action, related observations,
 *     and optional oscillation warning.
 */

import * as yaml from 'js-yaml';

import type { CandidateObservation, BaselineMetrics, DeduplicationResult } from '../engine/types';
import type { SeverityResult } from '../engine/severity-scorer';
import type { ConfidenceScore } from '../engine/confidence';
import type { PrometheusResult, GrafanaAlertResult } from '../adapters/types';
import type { DataSourceStatus } from '../adapters/types';
import type { ScrubbedOpenSearchResult } from '../safety/scrub-pipeline';

import { generateObservationId } from './file-naming';
import { validateOnWrite, type ObservationFrontmatter } from './schema-validator';
import {
  buildSeverityRationaleTable,
  buildMetricsTable,
  buildLogSection,
  buildAlertSection,
  buildOscillationWarning,
  generateTitle,
  generateSummary,
  type LlmAnalysisResult,
  type GovernanceFlags,
} from './templates';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Input required to generate a full observation report.
 *
 * Aggregates the candidate observation with all enrichment data from
 * the analytics pipeline.
 */
export interface ReportInput {
  /** The candidate observation from the detection/routing layer. */
  candidate: CandidateObservation;

  /** Deterministic severity scoring result (with optional LLM override). */
  severity: SeverityResult;

  /** Three-factor confidence score. */
  confidence: ConfidenceScore;

  /** Deduplication result for this candidate. */
  dedupResult: DeduplicationResult;

  /** Prometheus metric results used as evidence. */
  metrics: PrometheusResult[];

  /** Scrubbed OpenSearch log results. */
  logs: ScrubbedOpenSearchResult[];

  /** Grafana alert results. */
  alerts: GrafanaAlertResult;

  /** Baseline metrics for the service. */
  baseline: BaselineMetrics;

  /** Unique identifier for this observation run. */
  runId: string;

  /** Total tokens consumed during this observation. */
  tokensConsumed: number;

  /** Per-source connectivity status from the pre-run probe. */
  dataSourceStatus: Record<string, DataSourceStatus>;

  /** Governance flags (cooldown, oscillation). */
  governanceFlags: GovernanceFlags;

  /** LLM analysis result (optional — unavailable when LLM is skipped). */
  llmAnalysis?: LlmAnalysisResult;

  /**
   * SHA-256 fingerprint for this candidate.
   * Generated by the fingerprint module before report generation.
   */
  fingerprint: string;

  /**
   * Repository name for the service.
   * Falls back to `findServiceRepo()` if not provided on the candidate.
   */
  repo?: string;
}

// ---------------------------------------------------------------------------
// Report generation
// ---------------------------------------------------------------------------

/**
 * Generates a full observation report as a YAML-frontmatter + Markdown string.
 *
 * 1. Generates a unique observation ID.
 * 2. Builds the YAML frontmatter (validated against the schema).
 * 3. Builds the Markdown body with all required sections.
 * 4. Returns the combined string ready for file writing.
 *
 * @param input  Aggregated report input from the analytics pipeline.
 * @param now    Optional date for ID generation (defaults to current time).
 * @returns Object containing the generated ID and the full report content.
 */
export function generateReport(
  input: ReportInput,
  now: Date = new Date(),
): { id: string; content: string } {
  const id = generateObservationId(now);
  const frontmatter = buildFrontmatter(id, input, now);

  // Validate before writing
  validateOnWrite(frontmatter);

  const body = buildMarkdownBody(id, input);
  const content = `---\n${yaml.dump(frontmatter, { lineWidth: -1, noRefs: true })}---\n\n${body}`;

  return { id, content };
}

// ---------------------------------------------------------------------------
// Frontmatter builder
// ---------------------------------------------------------------------------

/**
 * Builds the YAML frontmatter object with all fields from TDD section 4.1.
 *
 * @param id     The generated observation ID.
 * @param input  Aggregated report input.
 * @param now    Timestamp for the report.
 * @returns Plain object matching `ObservationFrontmatterSchema`.
 */
export function buildFrontmatter(
  id: string,
  input: ReportInput,
  now: Date = new Date(),
): ObservationFrontmatter {
  return {
    id,
    timestamp: now.toISOString(),
    service: input.candidate.service,
    repo: input.repo ?? findServiceRepo(input.candidate.service),
    type: input.candidate.type,
    severity: input.severity.override?.accepted
      ? (input.severity.override.new_severity as 'P0' | 'P1' | 'P2' | 'P3')
      : input.severity.severity,
    confidence: parseFloat(input.confidence.composite.toFixed(2)),
    triage_status: input.governanceFlags.cooldown_active ? 'cooldown' : 'pending',
    triage_decision: null,
    triage_by: null,
    triage_at: null,
    triage_reason: null,
    defer_until: null,
    cooldown_active: input.governanceFlags.cooldown_active,
    linked_prd: null,
    linked_deployment: null,
    effectiveness: null,
    effectiveness_detail: null,
    observation_run_id: input.runId,
    tokens_consumed: input.tokensConsumed,
    fingerprint: input.fingerprint,
    occurrence_count: input.candidate.occurrence_count ?? 1,
    data_sources: {
      prometheus: input.dataSourceStatus.prometheus ?? 'not_configured',
      grafana: input.dataSourceStatus.grafana ?? 'not_configured',
      opensearch: input.dataSourceStatus.opensearch ?? 'not_configured',
      sentry: input.dataSourceStatus.sentry ?? 'not_configured',
    },
    related_observations: input.dedupResult.existing_observation_id
      ? [input.dedupResult.existing_observation_id]
      : [],
    oscillation_warning: input.governanceFlags.oscillation_warning,
  };
}

// ---------------------------------------------------------------------------
// Markdown body builder
// ---------------------------------------------------------------------------

/**
 * Builds the full Markdown body for the observation report.
 *
 * Sections (TDD section 3.9.2):
 *   1. Title
 *   2. Summary
 *   3. Severity Rationale (table with 5 factors + weighted total)
 *   4. Evidence: Metrics (Prometheus)
 *   5. Evidence: Logs (OpenSearch) — optional
 *   6. Evidence: Alerts (Grafana) — optional
 *   7. Root Cause Hypothesis (with disclaimer)
 *   8. Recommended Action
 *   9. Related Observations
 *  10. Oscillation Warning — optional
 */
export function buildMarkdownBody(id: string, input: ReportInput): string {
  const sections: string[] = [];

  // Title
  sections.push(
    `# Observation: ${input.llmAnalysis?.title ?? generateTitle(input)}\n`,
  );

  // Summary
  sections.push(
    `## Summary\n\n${input.llmAnalysis?.summary ?? generateSummary(input)}\n`,
  );

  // Severity Rationale Table
  sections.push(`## Severity Rationale\n`);
  sections.push(buildSeverityRationaleTable(input.severity));
  if (input.severity.override?.accepted) {
    sections.push(
      `\n**LLM Override**: ${input.severity.override.original_severity} -> ${input.severity.override.new_severity}. Justification: ${input.severity.override.justification}\n`,
    );
  }

  // Evidence: Metrics
  sections.push(`## Evidence\n`);
  sections.push(`### Metrics (Prometheus)\n`);
  sections.push(buildMetricsTable(input.metrics, input.baseline));

  // Evidence: Logs
  if (input.logs.length > 0) {
    sections.push(`### Logs (OpenSearch)\n`);
    sections.push(buildLogSection(input.logs));
  }

  // Evidence: Alerts
  if (input.alerts.alerts.length > 0) {
    sections.push(`### Alerts (Grafana)\n`);
    sections.push(buildAlertSection(input.alerts));
  }

  // Root Cause Hypothesis
  sections.push(`## Root Cause Hypothesis\n`);
  sections.push(
    `> **Note: This is a hypothesis generated by the intelligence engine, not a\n> confirmed root cause. Verify before acting.**\n`,
  );
  sections.push(
    `\n${input.llmAnalysis?.rootCauseHypothesis ?? 'LLM analysis unavailable.'}\n`,
  );

  // Recommended Action
  sections.push(`## Recommended Action\n`);
  sections.push(
    `${input.llmAnalysis?.recommendedAction ?? 'Manual investigation required.'}\n`,
  );

  // Related Observations
  sections.push(`## Related Observations\n`);
  if (input.dedupResult.existing_observation_id) {
    sections.push(
      `- ${input.dedupResult.existing_observation_id} (${input.dedupResult.reason})\n`,
    );
  } else {
    sections.push(`None (first occurrence of this pattern).\n`);
  }

  // Oscillation Warning (if applicable)
  if (input.governanceFlags.oscillation_warning) {
    sections.push(buildOscillationWarning(input.governanceFlags.oscillation_data));
  }

  return sections.join('\n');
}

// ---------------------------------------------------------------------------
// Service-to-repo fallback
// ---------------------------------------------------------------------------

/**
 * Fallback repo name derivation when repo is not explicitly provided.
 *
 * Converts a service name to a plausible repository name by
 * replacing whitespace/underscores with hyphens and lowercasing.
 *
 * @param serviceName  The canonical service name.
 * @returns A plausible repo name.
 */
export function findServiceRepo(serviceName: string): string {
  return serviceName.toLowerCase().replace(/[\s_]+/g, '-');
}
