#!/usr/bin/env bash
# reviewer-chain-render.sh — deterministic renderer for reviewer-chains.yaml.
#
# Pure function. Reads JSONL records of {id, weight, threshold} on stdin,
# emits a deterministic YAML document on stdout:
#   - sorted by weight ASC, ties broken by id ASC (lex)
#   - same input order/byte-equality across replays
#
# Used by phase-15 module's sort-and-render step. Isolated from the rest
# of the phase so it is unit-testable and independent of the catalog
# file format.
#
# Contract:
#   exit 0 = wrote rendered yaml; exit 1 = malformed input.
#
# References: SPEC-033-3-03 FR-9, NFR ordering determinism.

set -uo pipefail

render_reviewer_chain() {
  if ! command -v jq >/dev/null 2>&1; then
    echo "[reviewer-chain-render] jq not on PATH" >&2
    return 1
  fi
  # Collect input
  local input
  input="$(cat)"
  if [[ -z "$input" ]]; then
    echo "# Auto-generated by setup-wizard phase 15. Do not edit by hand."
    echo "specialists: []"
    return 0
  fi
  # Validate via jq, then sort.
  local sorted
  sorted="$(printf '%s\n' "$input" \
    | jq -c -s 'sort_by(.weight, .id)')" \
    || { echo "[reviewer-chain-render] malformed input" >&2; return 1; }
  echo "# Auto-generated by setup-wizard phase 15. Do not edit by hand."
  echo "specialists:"
  printf '%s\n' "$sorted" | jq -r '.[] | "  - id: \(.id)\n    weight: \(.weight)\n    threshold: \(.threshold)"'
}

# Dispatch shim (callable as a standalone executable).
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  render_reviewer_chain
fi
